import { FC, useContext, useState } from "react";
import { addWord } from "./../../api/wordApi";
import { ServerContext } from "../../context/ServerUrlContext";
import { Word } from "../../types/words";

interface AddWordProps {
  setData: React.Dispatch<React.SetStateAction<Word[]>>; // Allow modifying table data directly
}

//work ok
const AddWord: FC<AddWordProps> = ({ setData }) => {
  const [enWord, setEnWord] = useState("");
  const [heWord, setHeWord] = useState("");
  const serverUrl = useContext(ServerContext);

  const handleAddWord = async (ev: React.FormEvent<HTMLFormElement>) => {
      ev.preventDefault();
      console.log("At handleAddWord the enWord & heWord are:", enWord, heWord);

      // Create a temporary word object (assuming _id is generated by the backend)
      const tempWord: Word = {
        _id: Math.random().toString(36).substring(7), // Temporary ID
        en_word: enWord,
        he_word: heWord,
        __v: 0
      };

      // **1️⃣ Optimistically Update the UI**
      setData((prevData) => [tempWord, ...prevData]); // Show new word instantly

    try {  
      const response = await addWord(serverUrl, enWord, heWord);
      if (!response) {
        window.alert("Add word failed!");
        throw new Error("No response from axios at handleAddWord");
      }

      // Reset the form fields by calling the form's reset method
      (ev.target as HTMLFormElement).reset();

    } catch (error) {
      console.error(error);
    }
  };

  return (
    <>
      <div className="form-container">
        <form onSubmit={handleAddWord} className="form">
          <input
            className="addWordFormInput relative right-2 w-56 indent-12"
            type="text"
            placeholder="English Word"
            onInput={(ev) => setEnWord((ev.target as HTMLInputElement).value)}
          ></input>
          <input
            className="addWordFormInput relative w-60 addHe"
            type="text"
            placeholder="Hebrew Word"
            onInput={(ev) => setHeWord((ev.target as HTMLInputElement).value)}
          ></input>
          <button className="relative left-2.5 h-9 mt-1 py-1" type="submit">
            Add Word
          </button>
        </form>
      </div>
    </>
  );
};

export default AddWord;
